### ISSUE TITLE
Reading Group Feedback

### ISSUE THREAD

**Issue by jssmith1** [DeveloperLiberationFront/iTrustInterviews#445]
### Intro:
- [x] Security critical written in java
- [x] parallel construction in contribution bullets add for example to the second
- [x] more specifically instead of consequently

### Tasks:
- [x] More sonsisten template for all tasks (what is a correct approach)
- [x] an RSA
- [x] his description -> he illustrates
- [x] Although we are not specifically studying task completion time, we do report it

#### T2
- [x] Suggest using secure reandom, a more secure alternative

#### T3
- [x] More about the fix... need to find another location
- [x] what is JSP
 
#### T4
- [x] Therefore, a correct solution would use prepared statements

### Limitations:
- [x] Remove the first sentence
- [x] Remove example of type of task we didn't study
- [x] reprhase questions might differ based on experience
- [x] The fact that the study was conduced in... raises a threat to external...
- [x] Working outside their normal work->development environments
- [x] (s)he

### Assumption Analysis
- [x] process process
- [x] participant's typo

**Comment by jssmith1** [comment]
More in: b0fce41bb05c39d5859025ef76aaad6e22afe26a
